### ISSUE TITLE
Enable login to Google

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-eclipse-tools#342]
This issue is a top-level issue to track adding a login feature to our plugins.

Like in #283, this can be done in several steps.

- [x] Create a plugin skeleton
- [x] Add a no-op login menu item and a toolbar button
- [x] Implement `IElementUpdater` to update corresponding UI elements with the login status (e.g., if logged in, then label should be _Logout as XXX_, and change icon to indicate login status)
- [x] Check in code that actually tests if we are properly authorized (not unit tests, but e.g., an actual menu item on Eclipse)
- [x] Create a valid credential that passes the above test
- [x] Implement GPE-style login screen (i.e., instead of users entering verification code manually) (#398)
- [x] Inject client ID and client secret at compile tile (e.g., using `org.codehaus.mojo`)
- [x] Create OAuth client ID and client secret (#425)
- [x] Use the ide-login library (#480)
- [x] Use an external browser for login (#480)
- [x] Logout (#462)
- [x] Enable persisting and reusing credentials (or access/refresh tokens?) (#397)
- [x] Convert `GoogleLoginService` as an OSGi service (#446)
- [x] OAuth scopes documentation (#461)

Other related issues:

- Refactor: from `.eclipse.appengine.login` to `.eclipse.login` and remove all `appengine` naming (#396)
- Refactor: E4 Dependency Injection (#395)
- Refactor: UI-safe class and UI-inducing class (along the similar line of `CloudSdkProvider` vs `CloudSdkPrompter`) (#394)
- Clear login credentials on exit from Eclipse (#459)
- Establish lifetime for login credentials (#460)
- Enhanced UI for login (#488)

**Comment by briandealwis** [comment]
Added a TODO for IElementUpdater to reflect login status

**Comment by chanseokoh** [comment]
Added a TODO; we decided the next plan is to add manual test code (into production which will of course eventually removed)

**Comment by briandealwis** [comment]
> Implement GPE-style login screen (i.e., instead of users entering verification code manually), and log in via local server

You don't need a local server — you just watch for redirects to your registered callback URL or the `urn:ietf:wg:oauth:2.0:oob`-style URNs.  That callback URL can be `https://localhost`, but it doesn't actually require setting up a web server.

**Comment by chanseokoh** [comment]
For future reference:

So far, we've created the following issues against Google Java OAuth libraries to generate OGSi metadata. (Thanks, @elharo.)

https://github.com/google/google-oauth-java-client/issues/125
https://github.com/google/google-http-java-client/issues/328
https://github.com/google/google-api-java-client/issues/1018

**Comment by chanseokoh** [comment]
Login is now functional. Closing.
